#!/bin/sh

printf "Creating symbolic links to dot files..."
for name  in dot/* ; do
  target="$HOME/.`basename $name`"
  if [ -e "$target" ]; then
    if [ ! -L "$target" ]; then
      echo "WARNING: $target exists but is not a symlink."
      echo Backuping file $target to "$target"_old
      mv $target $(target)_old
    fi
  else
    echo "Symlinking  $target"
    ln -s "$PWD/$name" "$target"
  fi
done
echo "done"

printf "Fetching dein.vim(Bundler manager)..."
curl -s -L https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | bash -s $HOME/.cache/dein.vim &> /dev/null

if [ "$?" != "0" ];
then
  echo "Dein.vim installation failed"
  exit 1
else
  echo "done"
fi

solarized_dir=$HOME/solarized
printf "Installing Solarized..."
if [ ! -d "$solarized_dir" ]; then
  git clone https://github.com/altercation/solarized.git $solarized_dir
else
  echo "done"
fi

if ! type "brew" > /dev/null 2>&1; then
  echo "Homebrew was not found, please install homebrew to continue: http://brew.sh/"
  exit 1;
else
  echo "Updating brew formulas, it may take few minutes."
  brew update

  echo "Installing required brew formulas."
  brew bundle
fi

vim -u ~/.vimrc.bundles +"call dein#update()" +qa

echo "Installation completed"
