#!/bin/sh

for name  in dot/* ; do
  target="$HOME/.`basename $name`"
  if [ -e "$target" ]; then
    if [ ! -L "$target" ]; then
      echo "WARNING: $target exists but is not a symlink."
      echo Backuping file $target to "$target"_old
      mv $target $(target)_old
    fi
  else
    echo "Symlinking  $target"
    ln -s "$PWD/$name" "$target"
  fi
done

echo "Installing dein(vim plugin manager)"
curl -L -s https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | bash -s  ~/.config/nvim/plugin > /dev/null

pip2 install neovim --user
pip3 install neovim psutil --user

solarized_dir=~/solarized
echo "Checking for solarized: "
if [ ! -d "$solarized_dir" ]; then
  echo "Solarized was not found cloning it"
  git clone https://github.com/altercation/solarized.git $solarized_dir
else
  echo "Solarized is already installed"
fi

if ! type "brew" > /dev/null 2>&1; then
  echo "Homebrew was not found, please install homebrew to continue: http://brew.sh/"
  exit;
else
  echo "Updating brew formulas, it may take few minutes."
  brew update

  echo "Installing required brew formulas."
  brew bundle
fi

#nvim -u ~/.vimrc.bundles +BundleInstall +qa
