let mapleader = ","

set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile
set showcmd
set incsearch
set laststatus=2

if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif


set encoding=utf8
set tabstop=2 shiftwidth=2 expandtab

syntax on
set background=dark
let g:solarized_termcolors = 256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized

set hlsearch          " hilight searches by default

set number
set showmode
set autoindent
set autoindent
set pastetoggle=<F2>
set ruler

" listen to external change in the file
set autoread


set showmatch
set showcmd
set report=0
" delete the current line
set backspace=eol,start,indent
set visualbell
set ttyfast

" set clipboard to unmaed
set clipboard=unnamed

set backupdir=~/.vim/tmp
set dir=~/.vim/tmp

set history=200

" Let vim knows I'm using zsh so that it can take advantage of completion and
" other stuff
let &shell="zsh"

" stores the current cursor and command history
if has('nvim')
  set viminfo='100,\"1000,:40,%,n~/.nviminfo
else
  set viminfo='100,\"1000,:40,%,n~/.viminfo
endif
au BufReadPost * if line("'\"")|execute("normal `\"")|endif
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

set modeline
" set background=dark
" set cursorline

set foldmethod=marker
set fmr={{{,}}}
set foldlevel=0
" Toggle fold in which cursor is current on
nnoremap <space> @=((foldclosed(line(".")) < 0) ? 'zc' : 'zo')<CR>

" Default leader is set to \, with ',' I don't have to strech my finger to hit it
nmap <silent> <leader>h :silent :nohlsearch<CR>
nmap <silent> <leader>ct :TlistToggle<CR>
nmap <leader>n :silent :NERDTreeToggle<CR>


" Start interactive EasyAlign in visual mode
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign with a Vim movement
nmap <Leader>a <Plug>(EasyAlign)
nmap <leader>fw :FixWhitespace<CR>

" CtlP mapping to match most used command-t mappings
let g:ctrlp_map = '<leader>t'
let g:ctrlp_prompt_mappings = { 'PrtSelectMove("j")': ['<c-p>', '<down>'], 'PrtSelectMove("k")': ['<c-n>', '<up>'] }
let g:ctrlp_prompt_mappings = { 'PrtHistory(-1)': ['<c-k>'], 'PrtHistory(1)': ['<c-j>'] }

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

if $HOME != $PWD && filereadable(".vimrc")
  source .vimrc
endif
