let mapleader = ","

set backspace=2   " Backspace deletes like most programs in insert mode
set nocompatible  " Use Vim settings, rather then Vi settings
set nobackup
set nowritebackup
set noswapfile
set showcmd
set incsearch
set laststatus=2 


if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif


set encoding=utf8
set tabstop=2 shiftwidth=2 expandtab

syntax on
set background=dark
let g:solarized_termcolors = 256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized

set hlsearch          " hilight searches by default

set number
set showmode
set autoindent
set autoindent
set pastetoggle=<F2>
set ruler

" listen to external change in the file
set autoread


set showmatch
set showcmd
set report=0
" delete the current line
set backspace=eol,start,indent
set visualbell
set ttyfast

" set clipboard to unmaed
set clipboard=unnamed

set backupdir=~/.vim/tmp
set dir=~/.vim/tmp

set history=200

" Let vim knows I'm using zsh so that it can take advantage of completion and
" other stuff
let &shell="zsh"

" stores the current cursor and command history
set viminfo='100,\"1000,:40,%,n~/.viminfo
au BufReadPost * if line("'\"")|execute("normal `\"")|endif
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

set modeline
" set background=dark
" set cursorline

set foldmethod=marker
set fmr={{{,}}}
set foldlevel=0
" Toggle fold in which cursor is current on
nnoremap <space> @=((foldclosed(line(".")) < 0) ? 'zc' : 'zo')<CR>

let Tlist_Ctags_Cmd='/usr/local/bin/ctags'

" Default leader is set to \, with ',' I won't strech my finger to hit it
nmap <silent> <leader>h :silent :nohlsearch<CR>

nmap <silent> <leader>ct :TlistToggle<CR>
nmap <leader>n :silent :NERDTreeToggle<CR>

" nmap <leader>ct :FixWhitespace<CR>


set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

