export EDITOR=vim
export LC_ALL="en_US.UTF-8"

export PYTHON_SITE_PACKAGES=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
export POWERLINE_PATH="$PYTHON_SITE_PACKAGES/powerline"
export SOLARIZED_PATH="$HOME/solarized"
